INSERT INTO user (name, email, password) VALUES ('pepin', 'pepicekkyblicek@pr.cz', 'smradoch');
INSERT INTO user (name, email, password) VALUES ('levakbob', 'levakbobak@pr.cz', 'smradoch');
INSERT INTO user (name, email, password) VALUES ('jozinzbazin', 'lovecslepic@pr.cz', 'smradoch');

INSERT INTO post (author, title, url, created_at, user_id) VALUES('levakbob', 'Some very interesting article', 'http://seznam.cz/', '2020-09-15', 2);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('pepin', 'Some uninteresting article', 'http://google.cz/', '2020-09-15', 1);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('jozinzbazin', 'Some article', 'http://nyan.cat', '2020-09-15', 3);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('pepin', 'Article', 'http://pepa.vyskup.com/', '2020-09-15', 1);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('pepin', 'Some very interesting article', 'http://seznam.cz/', '2020-09-15', 1);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('pepin', 'Some uninteresting article', 'http://google.cz/', '2020-09-15', 1);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('levakbob', 'Some article', 'http://nyan.cat', '2020-09-15', 2);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('levakbob', 'Article', 'http://pepa.vyskup.com/', '2020-09-15', 2);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('pepin', 'Some very interesting article', 'http://seznam.cz/', '2020-09-15', 1);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('jozinzbazin', 'Some uninteresting article', 'http://google.cz/', '2020-09-15', 3);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('jozinzbazin', 'Some article', 'http://nyan.cat', '2020-09-15', 3);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('pepin', 'Article', 'http://pepa.vyskup.com/', '2020-09-15', 1);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('levakbob', 'Some very interesting article', 'http://seznam.cz/', '2020-09-15', 2);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('levakbob', 'Some uninteresting article', 'http://google.cz/', '2020-09-15', 2);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('pepin', 'Some article', 'http://nyan.cat', '2020-09-15', 1);
INSERT INTO post (author, title, url, created_at, user_id) VALUES('jozinzbazin', 'Article', 'http://pepa.vyskup.com/', '2020-09-15', 3);