INSERT INTO post (title, url, created_at) VALUES('Some very interesting article', 'http://seznam.cz/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some uninteresting article', 'http://google.cz/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some article', 'http://nyan.cat', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Article', 'http://pepa.vyskup.com/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some very interesting article', 'http://seznam.cz/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some uninteresting article', 'http://google.cz/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some article', 'http://nyan.cat', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Article', 'http://pepa.vyskup.com/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some very interesting article', 'http://seznam.cz/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some uninteresting article', 'http://google.cz/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some article', 'http://nyan.cat', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Article', 'http://pepa.vyskup.com/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some very interesting article', 'http://seznam.cz/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some uninteresting article', 'http://google.cz/', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Some article', 'http://nyan.cat', '2020-09-15');
INSERT INTO post (title, url, created_at) VALUES('Article', 'http://pepa.vyskup.com/', '2020-09-15');